package br.edu.kelly.visao;

import br.edu.kelly.controle.Fila;
import br.edu.kelly.controle.Senha;
import br.edu.kelly.modelo.ConexaoSqlite;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Tela02GUI extends javax.swing.JFrame {

    private Fila fila;

    /**
     * Creates new form Tela02GUI
     */
    public Tela02GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jbAcompanhar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtDigitar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setBackground(new java.awt.Color(153, 204, 255));
        jFrame1.setResizable(false);


        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGap(122, 122, 122))
        );


        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGap(122, 122, 122))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(350, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jbAcompanhar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAcompanhar.setText("Acompanhar");
        jbAcompanhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAcompanharActionPerformed(evt);
            }
        });
        getContentPane().add(jbAcompanhar);
        jbAcompanhar.setBounds(150, 190, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Digite sua senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 60, 110, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/kelly/visao/1_Primary_logo_on_transparent_114x75.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 290, 110, 70);

        jtDigitar.setBackground(new java.awt.Color(230, 240, 249));
        getContentPane().add(jtDigitar);
        jtDigitar.setBounds(140, 110, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/kelly/visao/257.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 380);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAcompanharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAcompanharActionPerformed
        // TODO add your handling code here:
        String senhaPesquisada = jtDigitar.getText();
        String tipo = "" + senhaPesquisada.subSequence(0, 1);
        String tipoFila = null;
        try {
            ConexaoSqlite con = new ConexaoSqlite("fila_db");
            switch (tipo) {
                case "N":
                    tipoFila = "Normal";
                    break;
                case "P":
                    tipoFila = "Prioritaria";
                    break;
                case "F":
                    tipoFila = "Fies";
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Nenhuma senha existente contém este código.\nPor favor digite uam senha válida");
                    break;
            }
            fila = con.getFila(tipoFila);
            String tempo = con.tempoAtendimento(tipo);
            
            Senha senha = fila.senhaPesquisada(senhaPesquisada);
            if (senha != null) {
                new Tela03GUI(fila, senha, senhaPesquisada,tempo).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Não foi encontrada nenhuma senha com este código em nenhuma das filas!!");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Tela02GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbAcompanharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbAcompanhar;
    private javax.swing.JTextField jtDigitar;
    // End of variables declaration//GEN-END:variables
}
