package br.edu.kelly.visao;

import br.edu.kelly.controle.Fila;
import br.edu.kelly.controle.Senha;

public class Tela03GUI extends javax.swing.JFrame {
    private Fila f;
    private Senha s;
    private String cod;
    
    /**
     * Creates new form Tela03GUI
     */
    
    public Tela03GUI(Fila f, Senha s, String cod) {
        initComponents();
        this.f = f;
        this.s = s;
        jtMinhaSenha.setText(cod);
        jtPessoasFrente.setText(""+f.qtdSenhasAnteriores(s));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtMinhaSenha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtTempoAtendimento = new javax.swing.JTextField();
        jtPessoasFrente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Senha:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 80, 42, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tempo Atendimento:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 140, 20);

        jtMinhaSenha.setBackground(new java.awt.Color(230, 240, 249));
        jtMinhaSenha.setEnabled(false);
        getContentPane().add(jtMinhaSenha);
        jtMinhaSenha.setBounds(100, 80, 120, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/kelly/visao/1_Primary_logo_on_transparent_114x75.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 280, 120, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Pessoas na frente:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(33, 125, 113, 15);

        jtTempoAtendimento.setBackground(new java.awt.Color(230, 240, 249));
        jtTempoAtendimento.setEnabled(false);
        jtTempoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTempoAtendimentoActionPerformed(evt);
            }
        });
        getContentPane().add(jtTempoAtendimento);
        jtTempoAtendimento.setBounds(170, 160, 130, 20);

        jtPessoasFrente.setBackground(new java.awt.Color(230, 240, 249));
        jtPessoasFrente.setEnabled(false);
        jtPessoasFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPessoasFrenteActionPerformed(evt);
            }
        });
        getContentPane().add(jtPessoasFrente);
        jtPessoasFrente.setBounds(161, 122, 90, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/kelly/visao/257.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(400, 400));
        jLabel4.setMinimumSize(new java.awt.Dimension(400, 400));
        jLabel4.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 450, 380);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtTempoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTempoAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTempoAtendimentoActionPerformed

    private void jtPessoasFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPessoasFrenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPessoasFrenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jtMinhaSenha;
    private javax.swing.JTextField jtPessoasFrente;
    private javax.swing.JTextField jtTempoAtendimento;
    // End of variables declaration//GEN-END:variables
}
